os: linux
dist: bionic
sudo: true

services:
  - docker

before_script:
- sudo apt-get install -y astyle
- cd /home/travis/build/occlum/occlum; info=$(make format-check); if [ -n "$info" ]; then echo "Format error detected."; exit 1; fi

script:
- docker run -v /home/travis/build/occlum/occlum:/root/occlum occlum/occlum:0.12.0-ubuntu18.04 /bin/bash -c "cd /root/occlum; make submodule; SGX_MODE=SIM make; SGX_MODE=SIM make test"
