name: Occlum Docker Build and Push

# Triggers the workflow on pre-release events
on:
  release:
    types: [prereleased]

jobs:
  generate-centos-image:
      # GitHub Actions doesn't have CentOS VM provided
      runs-on: ubuntu-18.04

      steps:
      - name: Prepare tools
        run: |
          sudo apt-get update
          sudo apt-get install yum

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      - name: Build and Push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./tools
          dockerfile: ./tools/docker/Dockerfile.centos8.1
          repository: occlumbackup/occlum
          tags: "${{ env.RELEASE_VERSION }}-centos8.1"


  generate-ubuntu-image:
      runs-on: ubuntu-18.04

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      - name: Build and Push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./tools
          dockerfile: ./tools/docker/Dockerfile.ubuntu18.04
          repository: occlumbackup/occlum
          tags: "${{ env.RELEASE_VERSION }}-ubuntu18.04"
